# CMake generated Testfile for 
# Source directory: D:/金介然/大三下/编译课设/CODE
# Build directory: D:/金介然/大三下/编译课设/CODE/build_fresh
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(lexer_smoke_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Debug/lexer_smoke_tests.exe")
  set_tests_properties(lexer_smoke_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;79;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(lexer_smoke_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Release/lexer_smoke_tests.exe")
  set_tests_properties(lexer_smoke_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;79;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(lexer_smoke_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/MinSizeRel/lexer_smoke_tests.exe")
  set_tests_properties(lexer_smoke_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;79;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(lexer_smoke_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/RelWithDebInfo/lexer_smoke_tests.exe")
  set_tests_properties(lexer_smoke_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;79;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
else()
  add_test(lexer_smoke_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(lexer_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Debug/lexer_tests.exe")
  set_tests_properties(lexer_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;89;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(lexer_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Release/lexer_tests.exe")
  set_tests_properties(lexer_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;89;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(lexer_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/MinSizeRel/lexer_tests.exe")
  set_tests_properties(lexer_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;89;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(lexer_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/RelWithDebInfo/lexer_tests.exe")
  set_tests_properties(lexer_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;89;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
else()
  add_test(lexer_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(parser_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Debug/parser_tests.exe")
  set_tests_properties(parser_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;100;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(parser_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Release/parser_tests.exe")
  set_tests_properties(parser_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;100;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(parser_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/MinSizeRel/parser_tests.exe")
  set_tests_properties(parser_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;100;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(parser_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/RelWithDebInfo/parser_tests.exe")
  set_tests_properties(parser_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;100;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
else()
  add_test(parser_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bison_parser_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Debug/bison_parser_tests.exe")
  set_tests_properties(bison_parser_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;109;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bison_parser_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Release/bison_parser_tests.exe")
  set_tests_properties(bison_parser_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;109;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bison_parser_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/MinSizeRel/bison_parser_tests.exe")
  set_tests_properties(bison_parser_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;109;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bison_parser_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/RelWithDebInfo/bison_parser_tests.exe")
  set_tests_properties(bison_parser_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;109;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
else()
  add_test(bison_parser_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(semantic_tableset_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Debug/semantic_tableset_tests.exe")
  set_tests_properties(semantic_tableset_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;117;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(semantic_tableset_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Release/semantic_tableset_tests.exe")
  set_tests_properties(semantic_tableset_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;117;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(semantic_tableset_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/MinSizeRel/semantic_tableset_tests.exe")
  set_tests_properties(semantic_tableset_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;117;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(semantic_tableset_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/RelWithDebInfo/semantic_tableset_tests.exe")
  set_tests_properties(semantic_tableset_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;117;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
else()
  add_test(semantic_tableset_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(semantic_typepool_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Debug/semantic_typepool_tests.exe")
  set_tests_properties(semantic_typepool_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;125;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(semantic_typepool_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Release/semantic_typepool_tests.exe")
  set_tests_properties(semantic_typepool_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;125;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(semantic_typepool_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/MinSizeRel/semantic_typepool_tests.exe")
  set_tests_properties(semantic_typepool_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;125;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(semantic_typepool_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/RelWithDebInfo/semantic_typepool_tests.exe")
  set_tests_properties(semantic_typepool_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;125;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
else()
  add_test(semantic_typepool_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(semantic_declaration_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Debug/semantic_declaration_tests.exe")
  set_tests_properties(semantic_declaration_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;136;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(semantic_declaration_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Release/semantic_declaration_tests.exe")
  set_tests_properties(semantic_declaration_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;136;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(semantic_declaration_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/MinSizeRel/semantic_declaration_tests.exe")
  set_tests_properties(semantic_declaration_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;136;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(semantic_declaration_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/RelWithDebInfo/semantic_declaration_tests.exe")
  set_tests_properties(semantic_declaration_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;136;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
else()
  add_test(semantic_declaration_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(semantic_usage_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Debug/semantic_usage_tests.exe")
  set_tests_properties(semantic_usage_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;147;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(semantic_usage_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Release/semantic_usage_tests.exe")
  set_tests_properties(semantic_usage_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;147;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(semantic_usage_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/MinSizeRel/semantic_usage_tests.exe")
  set_tests_properties(semantic_usage_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;147;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(semantic_usage_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/RelWithDebInfo/semantic_usage_tests.exe")
  set_tests_properties(semantic_usage_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;147;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
else()
  add_test(semantic_usage_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(semantic_expression_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Debug/semantic_expression_tests.exe")
  set_tests_properties(semantic_expression_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;158;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(semantic_expression_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Release/semantic_expression_tests.exe")
  set_tests_properties(semantic_expression_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;158;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(semantic_expression_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/MinSizeRel/semantic_expression_tests.exe")
  set_tests_properties(semantic_expression_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;158;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(semantic_expression_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/RelWithDebInfo/semantic_expression_tests.exe")
  set_tests_properties(semantic_expression_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;158;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
else()
  add_test(semantic_expression_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(semantic_param_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Debug/semantic_param_tests.exe")
  set_tests_properties(semantic_param_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;169;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(semantic_param_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Release/semantic_param_tests.exe")
  set_tests_properties(semantic_param_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;169;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(semantic_param_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/MinSizeRel/semantic_param_tests.exe")
  set_tests_properties(semantic_param_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;169;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(semantic_param_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/RelWithDebInfo/semantic_param_tests.exe")
  set_tests_properties(semantic_param_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;169;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
else()
  add_test(semantic_param_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(semantic_gate_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Debug/semantic_gate_tests.exe")
  set_tests_properties(semantic_gate_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;182;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(semantic_gate_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Release/semantic_gate_tests.exe")
  set_tests_properties(semantic_gate_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;182;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(semantic_gate_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/MinSizeRel/semantic_gate_tests.exe")
  set_tests_properties(semantic_gate_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;182;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(semantic_gate_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/RelWithDebInfo/semantic_gate_tests.exe")
  set_tests_properties(semantic_gate_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;182;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
else()
  add_test(semantic_gate_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(codegen_template_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Debug/codegen_template_tests.exe")
  set_tests_properties(codegen_template_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;192;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(codegen_template_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/Release/codegen_template_tests.exe")
  set_tests_properties(codegen_template_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;192;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(codegen_template_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/MinSizeRel/codegen_template_tests.exe")
  set_tests_properties(codegen_template_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;192;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(codegen_template_tests "D:/金介然/大三下/编译课设/CODE/build_fresh/RelWithDebInfo/codegen_template_tests.exe")
  set_tests_properties(codegen_template_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;192;add_test;D:/金介然/大三下/编译课设/CODE/CMakeLists.txt;0;")
else()
  add_test(codegen_template_tests NOT_AVAILABLE)
endif()
