/* Auto-generated by pascc (M5 template stage). */
/* Source unit: _01_features */

#include <stdio.h>
#include <stdbool.h>

/* ---------- Runtime I/O helpers ---------- */
static int pas_read_int(void) { int v = 0; (void)scanf("%d", &v); return v; }
static void pas_write_int(int v) { (void)printf("%d", v); }
static void pas_writeln(void) { (void)printf("\n"); }

/* ---------- Global declarations ---------- */
int a1 = 0;
int b2 = 0;

/* ---------- Routine declarations ---------- */
/* TODO(T-028): emit translated procedure/function declarations here. */

int main(void) {
    /* ---------- Main translated statements ---------- */
    /* Core mapping targets:
       - assignment: x = expr;
       - if/else: if (cond) { ... } else { ... }
       - while: while (cond) { ... }
       - for: for (i = begin; i <= end; ++i) { ... }
       - read/readln: x = pas_read_int();
       - write/writeln: pas_write_int(expr); pas_writeln();
    */
    a1 = 12;
    b2 = 34;

    return 0;
}
