/* Auto-generated by pascc (M5 template stage). */
/* Source unit: _03_controlflow */

#include <stdio.h>
#include <stdbool.h>

/* ---------- Runtime I/O helpers ---------- */
static int pas_read_int(void) { int v = 0; (void)scanf("%d", &v); return v; }
static void pas_write_int(int v) { (void)printf("%d", v); }
static void pas_writeln(void) { (void)printf("\n"); }

/* ---------- Global declarations ---------- */
int i = 0;
int sum = 0;

/* ---------- Routine declarations ---------- */
/* TODO(T-028): emit translated procedure/function declarations here. */

int main(void) {
    /* ---------- Main translated statements ---------- */
    /* Core mapping targets:
       - assignment: x = expr;
       - if/else: if (cond) { ... } else { ... }
       - while: while (cond) { ... }
       - for: for (i = begin; i <= end; ++i) { ... }
       - read/readln: x = pas_read_int();
       - write/writeln: pas_write_int(expr); pas_writeln();
    */
    i = 0;
    sum = 0;
    while (i < 3) {
        if (i == 1) {
            sum = sum + 10;
        }
        else {
            sum = sum + i;
        }
        i = i + 1;
    }
    for (i = 1; i <= 2; ++i) {
        sum = sum + i;
    }
    for (i = 3; i >= 1; --i) {
        sum = sum + i;
    }

    return 0;
}
