/* Auto-generated by pascc (M5 template stage). */
/* Source unit: _04_routines */

#include <stdio.h>
#include <stdbool.h>

/* ---------- Runtime I/O helpers ---------- */
static int pas_read_int(void) { int v = 0; (void)scanf("%d", &v); return v; }
static void pas_write_int(int v) { (void)printf("%d", v); }
static void pas_writeln(void) { (void)printf("\n"); }

/* ---------- Global declarations ---------- */
int x = 0;

/* ---------- Routine declarations ---------- */
void inc1(int a) {
    x = x + a;
}

int add1(int v) {
    return v + 1;
}

int main(void) {
    /* ---------- Main translated statements ---------- */
    /* Core mapping targets:
       - assignment: x = expr;
       - if/else: if (cond) { ... } else { ... }
       - while: while (cond) { ... }
       - for: for (i = begin; i <= end; ++i) { ... }
       - read/readln: x = pas_read_int();
       - write/writeln: pas_write_int(expr); pas_writeln();
    */
    x = 1;
    inc1(2);
    x = add1 ( x );

    return 0;
}
