/* Auto-generated by pascc (M5 template stage). */
/* Source unit: _05_realmap */

#include <stdio.h>
#include <stdbool.h>

/* ---------- Runtime I/O helpers ---------- */
static int pas_read_int(void) { int v = 0; (void)scanf("%d", &v); return v; }
static void pas_write_int(int v) { (void)printf("%d", v); }
static void pas_writeln(void) { (void)printf("\n"); }

/* ---------- Global declarations ---------- */
float x = 0;

/* ---------- Routine declarations ---------- */
float addh(float v) {
    return v + 0.5;
}

int main(void) {
    /* ---------- Main translated statements ---------- */
    /* Core mapping targets:
       - assignment: x = expr;
       - if/else: if (cond) { ... } else { ... }
       - while: while (cond) { ... }
       - for: for (i = begin; i <= end; ++i) { ... }
       - read/readln: x = pas_read_int();
       - write/writeln: pas_write_int(expr); pas_writeln();
    */
    x = 1.25;
    x = addh ( x );

    return 0;
}
