#include "compiler_driver.h"

#include <filesystem>
#include <fstream>
#include <sstream>

#include "error_codes.h"
#include "lexer.h"
#include "log.h"

namespace fs = std::filesystem;

int CompilerDriver::run(const std::string& inputPath) {
    if (!hasPasExtension(inputPath)) {
        logutil::error("E001", "Input file must have .pas extension: " + inputPath);
        return toExitCode(ErrorCode::InvalidExtension);
    }

    fs::path source(inputPath);
    if (!fs::exists(source)) {
        logutil::error("E002", "Input file does not exist: " + inputPath);
        return toExitCode(ErrorCode::InputNotFound);
    }

    std::ifstream in(source);
    if (!in.good()) {
        logutil::error("E003", "Input file is not readable: " + inputPath);
        return toExitCode(ErrorCode::InputUnreadable);
    }

    std::ostringstream buffer;
    buffer << in.rdbuf();
    const std::string sourceCode = buffer.str();

    Lexer lexer;
    const auto tokens = lexer.tokenize(sourceCode);

    const std::string outputPath = deriveOutputPath(inputPath);
    std::ofstream out(outputPath, std::ios::trunc);
    if (!out.good()) {
        logutil::error("E004", "Failed to create output .c file: " + outputPath);
        return toExitCode(ErrorCode::OutputCreateFailed);
    }

    out << "/* Auto-generated by pascc (skeleton stage). */\n";
    out << "#include <stdio.h>\n\n";
    out << "int main(void) {\n";
    out << "    /* TODO: replace skeleton output with translated Pascal-S program */\n";
    out << "    return 0;\n";
    out << "}\n";

    logutil::info("Input:  " + source.string());
    logutil::info("Output: " + outputPath);
    logutil::info("Tokenized items (skeleton): " + std::to_string(tokens.size()));
    return toExitCode(ErrorCode::Ok);
}

std::string CompilerDriver::deriveOutputPath(const std::string& inputPath) {
    fs::path source(inputPath);
    source.replace_extension(".c");
    return source.string();
}

bool CompilerDriver::hasPasExtension(const std::string& path) {
    fs::path p(path);
    return p.has_extension() && p.extension() == ".pas";
}
